### ISSUE TITLE
Installation Steps

### ISSUE THREAD

**Issue by plunkettscott** [tristanrobert/foreman_fog_proxmox#24]
# Installation Steps

## Prerequisites

Please check (put an X between the brackets) the following items before posting any issue:

* [x] Have you check that no [issue](https://github.com/tristanrobert/foreman_proxmox/issues) already exists and could match yours?

* [x] Have you read the [contributing code](CONTRIBUTING.md)?

## Description

  Looking for information on how to install this.

## Environment

  Brand new foreman with only provisioning setup completed.

## Version

  v0.1.0

## Steps to reproduce

  N/A

### Expected behavior

Plugin to be installed and to see a new provisioning resource.

### Actual behavior

N/A

### Reproduces how often:

N/A

## Additional Information
N/A

**Comment by tristanrobert** [comment]
Hello,
it is still an alpha release. I am sorry that the installation process is not yet production friendly. It will be soon from 0.2.0: I will publish the gems and I will ask foreman team how to do with their installer. Before that, you can still test it from the source. You can see [development section](https://github.com/tristanrobert/foreman_proxmox#development) with docker container. You can also do the same from a foreman clone repo.

**Comment by tristanrobert** [comment]
@plunkettscott You can now install the [gem](https://rubygems.org/gems/the_foreman_proxmox) in 0.3.1. It will be easier. I am now working in #25.

**Comment by plunkettscott** [comment]
@tristanrobert I installed the gem, however, I don't see it as an available plugin inside of Foreman. Any suggestions on how to get it to be an available plugin?

**Comment by tristanrobert** [comment]
Could you please show logs. Which Foreman version have you installed?
If you [install from source](https://theforeman.org/manuals/1.17/index.html#3.4InstallFromSource) it works. To install from packages, you should better wait their availability, see #25.

**Comment by tristanrobert** [comment]
I have completed the docs. See the readme.md file. I hope it will help you.
