### ISSUE TITLE
In a cluster, the correct Proxmox host isn't always queried

### ISSUE THREAD

**Issue by RedChops** [tristanrobert/foreman_fog_proxmox#30]
**Describe the bug**
I have a cluster of three Proxmox nodes. After adding one of the nodes' IP address to set up the Compute Resource, all of the VMs are properly listed in the Virtual Machines tab. Using an example of the issue, a guest with VMID 117 is currently running on vmhost1 (this is also the node that I'm connected to, but it happens seemingly at random as many guests on this node are properly connected to) and is reported running on that host if I run `pvesh get /cluster/resources`. If I click on the VM in the tab I get an error that states  `"Configuration file 'nodes/vmhost3/qemu-server/117.conf' does not exist"` which would make sense, as that guest is not running on vmhost3. I can't really deduce what causes the plugin to query the incorrect host though, there doesn't seem to be a pattern to me.

**To Reproduce**
1. Have Proxmox cluster of three nodes or more
2. Click on any guest in the Virtual Machines tab

**Expected behavior**
Virtual machine guest information is displayed

**Actual behavior**
Sometimes virtual machine guest is displayed, sometimes above error is shown

**Desktop (please complete the following information):**
 - OS: Linux, Windows, MacOS
 - Browser Firefox, Chrome, Safari
 - Version all

**Additional context**
I looked through the source of this plugin, but I don't know ruby all that well so I couldn't really figure out where the 'node' part of the query comes from or why it would be polling the incorrect one only 50% of the time. The plugin does seem to correctly show guests on other nodes from the one that I'm connected to sometimes.

**Comment by tristanrobert** [comment]
Hello, choosing the node you want to compute with is not still available. You can only compute in one node. By default, the plugin gets the first one in the collection given by fog-proxmox. Indeed, it's a feature that could be added.

**Comment by tristanrobert** [comment]
It will be fix when #31 is added.

**Comment by RedChops** [comment]
Thanks, I appreciate it

**Comment by tristanrobert** [comment]
Fixed with #31 in 0.5.0 release
