### ISSUE TITLE
LXC presence break VM display

### ISSUE THREAD

**Issue by hartmel** [tristanrobert/foreman_fog_proxmox#32]
**Describe the bug**
If there is a LXC in the cluster, listing VMs in Foreman is broken.
The URL to get configuration used is /api2/json/nodes/mynode/qemu/[ID]/config. It result as a 500 error response from Proxmox API, when ID is a LXC.
All the other requests (VM) have 200 but these valid results are not shown in Foreman. 

**To Reproduce**
Create a LXC on proxmox and browse the VM tab in the compute resource in Foreman.

**Expected behavior**
LXC is correctly identified.
An error on an item (VM or LXC) doesn't prevent to display items for which the API calls are OK.

**Screenshots**
![image](https://user-images.githubusercontent.com/4541209/43995760-e0f933ce-9db4-11e8-937f-4b4439657e5d.png)
![image](https://user-images.githubusercontent.com/4541209/43995765-ecd928de-9db4-11e8-9f9c-0ba835e1f5f2.png)

`10.10.10.10 - apiuser@myrealm [11/08/2018:22:09:53 +0200] "GET /api2/json/nodes/mynode/qemu/107/config HTTP/1.1" 500 13
`

Proxmox VE version : 5.2-2

**Comment by tristanrobert** [comment]
The screenshot shows that you use an non stable release of the foreman_fog_proxmox plugin.
The containers feature will be very soon released in few days #7

**Comment by tristanrobert** [comment]
Fixed with #7 in 0.5.0 release
