### ISSUE TITLE
Version 0.5 dependency problem

### ISSUE THREAD

**Issue by selund** [tristanrobert/foreman_fog_proxmox#33]
**Describe the bug**
Depending on deface 1.3 makes it impossible to install this module on a foreman 1.18 installation on debian 9.5

**To Reproduce**
add gem 'foreman_fog_proxmox', :git => "https://github.com/tristanrobert/foreman_fog_proxmox.git"
to ~foreman/bundler.d/Gemfile.local.rb and run https://github.com/tristanrobert/foreman_fog_proxmox.git as foreman 

**Screenshots**
Bundler could not find compatible versions for gem "deface":
  In snapshot (Gemfile.lock):
    deface (= 1.2.0)

  In Gemfile:
    deface (= 1.2.0)

    foreman_dhcp_browser (= 0.0.8) was resolved to 0.0.8, which depends on
      deface

    foreman_fog_proxmox was resolved to 0.5.0, which depends on
      deface (~> 1.3)

    foreman_monitoring (= 1.0.1) was resolved to 1.0.1, which depends on
      deface (< 2.0)

    foreman_monitoring (= 1.0.1) was resolved to 1.0.1, which depends on
      deface (< 2.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by tristanrobert** [comment]
It will be fixed with #34
