### ISSUE TITLE
Some settings in compute profiles do not save on submit

### ISSUE THREAD

**Issue by RedChops** [tristanrobert/foreman_fog_proxmox#35]
**Describe the bug**
When creating a new compute profile, or editing an existing one, a few settings that I've tried don't save when I submit the form. Under CPU, the only setting that will save is the 'Spectre-CTRL' checkbox. Under memory, 'Minimum memory', 'shares' and 'Ballooning Device' do not save. Upon form reload, all mentioned items revert to their default state. I've noticed no errors when submitting.

When I go to use this profile during guest creation, if I set any one of these options that do not save under the 'Virtual Machine' tab, they do get correctly sent to Proxmox.

**Comment by tristanrobert** [comment]
It is a bug with foreman javascript widget `ui.byteSpinner` in [foreman/webpack/assets/javascripts/jquery.ui.custom_spinners.js](https://github.com/theforeman/foreman/blob/c4693b378424ac1d9cb5aab9cd5e84b83a861479/webpack/assets/javascripts/jquery.ui.custom_spinners.js#L31).
The same form ` foreman_fog_proxmox/app/views/compute_resources_vms/form/proxmox/server/_config.html.erb ` works in vm creation but not in profile creation.
Solution: add tfm.numFields.initAll at ContentLoad page to force init byte spinner in form.

**Comment by tristanrobert** [comment]
Ballooning memory is not implemented. 
```
If ballooned 
  memory = min_memory + shares
end
```
It will be added in 0.5.2 too.

**Comment by tristanrobert** [comment]
Fixed in 0.5.2
