### ISSUE TITLE
Use next available vmid

### ISSUE THREAD

**Issue by selund** [tristanrobert/foreman_fog_proxmox#37]
It would be a good thing to be able to create a new vm without having to know what the next available vmid is.
At the moment I'm looking at automatic deployment of vm's based on messages comming from a RabbitMQ queue. The system creating these messages have no idea of what vmid's are available in my PVE cluster.

**Comment by tristanrobert** [comment]
It is already the [case](https://github.com/tristanrobert/foreman_fog_proxmox/blob/6c8e27d3f2a40851e03c75fa3359229bbae2694c/app/models/foreman_fog_proxmox/proxmox.rb#L408).

**Comment by selund** [comment]
Ok, then the problem is that a compute profile requires a vmid set.

**Comment by selund** [comment]
Yes, and that results in a situation where a compute profile ends up with a vmid. Setting a vmid on a profile locks the profile to a given vm thus making it unusable for generic profiles like "2core4GBram100GBdisk" for instance. 

On one hand I can understand the reason for wanting to be able to set vmid, but on the other hand, it might be better to just assign the next one when the vm is created and not have it as an option to set at all.

**Comment by tristanrobert** [comment]
I understand now the feature you ask.

**Comment by selund** [comment]
I might be wrong, but wouldn't changing :required => true to :required => false  [here](https://github.com/tristanrobert/foreman_fog_proxmox/blob/cee95b653e2ddbaf3570a770e4921776fa210eda/app/views/compute_resources_vms/form/proxmox/_general.html.erb#L22) be enough?

**Comment by tristanrobert** [comment]
vmid is required by proxmox. It should be next_vmid by default and it could be modified by user. Problem is that profile and vm are using same form. The code must be improved.

**Comment by tristanrobert** [comment]
Proxmox requires a vmid. The issue is that vm and profile shares the same form. It is a foreman design. I think it could be improved.
