### ISSUE TITLE
What versions of foreman are actually supported? 

### ISSUE THREAD

**Issue by moofishies** [tristanrobert/foreman_fog_proxmox#38]
[Here](https://projects.theforeman.org/issues/2186) I see "It is only available with Foreman 1.17" but on the Github project README I see "Foreman >= 1.17". I'm unsure which of these it actually means. 

I've been trying to get this to work for hours and was very frustrated when I say that only 1.17 works on the feature request, because I assumed 1.19 would work from reading the README.

**Comment by sandromodarelli** [comment]
It works with foreman 1.19. tested on centos installation, plugin installed manually with gem install and Ruby upgraded to 2.4

**Comment by moofishies** [comment]
What order did you install the software? I installed nodejs, ruby 2.4, but got an error when I tried to install foreman: 

`foreman-installer
/opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- kafo (LoadError)
        from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/sbin/foreman-installer:3:in `<main>'
`

**Comment by moofishies** [comment]
I loaded an older snapshot and tried to install in this order: nodejs, foreman 1.19, ruby 2.4. Then I tried to install the foreman_fog_proxmox gem both by `gem install foreman_fog_proxmox` and adding 'gem 'foreman _fog_proxmox'' to the bundler.d/Gemfile.local.rb and restarting foreman. But after restarting foreman I still do not see Proxmox listed as an available service. 

I don't believe I missed any steps so I'm not sure why it is still not showing up.

**Comment by sandromodarelli** [comment]
You have to restart https too

**Comment by moofishies** [comment]
Yep, that's literally all I needed to do lol. After `systemctl restart httpd` the provider shows up. 

It would be cool if that was included in the documentation somewhere, but in the end I probably should've guessed that haha.

**Comment by moofishies** [comment]
Now it seems that I'm not able to create the Proxmox compute Resource. I believe I've put in all of the correct information, REST API URL, credentials, and the root and node certificates. https://i.imgur.com/6pAZpwU.png

Are there any changes I need to make before this will work? When I click Test failed it just tries to connect and says "Test failed" again. And the Node never shows up on the drop down at the bottom of the screen.

**Comment by sandromodarelli** [comment]
@moofishies It's selinux. Disable it.
I think you have to offer me a good beer ;)

**Comment by moofishies** [comment]
@sandromodarelli you are the man :) That fixed it now it connected and I can hopefully start using it. 

My favorite beer is a sour called duchesse de bourgogne :)
