### ISSUE TITLE
"property is not defined in schema and the schema does not allow additional properties" when creating a new PVE VM

### ISSUE THREAD

**Issue by moofishies** [tristanrobert/foreman_fog_proxmox#40]
I've been busy but I finally got to the point that I am ready to start provisioning VMs with Foreman 1.19. When I go to create a new host I fill in the required fields and hit submit and see the error "Oops, we're sorry but something went wrong undefined method `[]' for nil:NilClass"

I investigated the /var/log/foreman/production.log logs and found this related error: [https://pastebin.com/WrXV4cj8](https://pastebin.com/WrXV4cj8)

I think Proxmox is not accepting one of the fields that Foreman is trying to pass it? I've tried to create a new host several times and I think I am only filling in the fields that are absolutely required. 

**To Reproduce**
1. Click Hosts > Create Host
2. Fill in required fields:
     a. Under Host fill in Name, Deploy On (Proxmox), Environment, Puppet Master, Puppet CA
     b. Under Virtual Machine change the VM ID to an open ID. All other settings are left default to try and troubleshoot the bug. 
     c. Under Operating System fill in Architecture, Operating System, Provisioning Method (Network Based), Build (checked), Media, Partition Table, PXE Loader, Root Pass. Verify settings with the Resolve button at the bottom of the page. 
     d. Under interfaces edit the default interface. Fill in Type (Interface), Mac Address (used 00:11:22:33:44:55), Device Identifer (net0), DNS Name, Domain, IPv4 Subnet, IPv4 Address. Change the NIC Card to VirtIO paravirtualized. 
3. Click Submit
4. After clicking Submit get error "Oops, we're sorry but something went wrong undefined method `[]' for nil:NilClass"

**Expected behavior**
Expect Foreman to provision a new VM on Proxmox

**Comment by moofishies** [comment]
Here is a screenshot of the error: https://i.imgur.com/nTxkI2b.png

More details:
CentOS 7
Foreman 1.19
Ruby 2.3
Proxmox 5.2-10

CentOS 7 VM is hosted on the Proxmox Server.

**Comment by tristanrobert** [comment]
Hello, did you compiled plugin assets?
`bundle exec bin/rake plugin:assets:precompile[foreman_fog_proxmox]`

**Comment by moofishies** [comment]
Hm no I hadn't, I didn't realize that was required. I don't think I saw it in the steps to install with CentOS. 

I'll try this tomorrow and report back.

**Comment by moofishies** [comment]
I had installed foreman_fog_proxmox with `gem install foreman_fog_proxmox` and not by using the Gemfile.local.rb file. 

I'm trying to run the precompile command but can't seem to get it to work:

`[root@foreman1 bundler.d]# ll`
`total 16`
`-rw-r--r--. 1 root root  36 Aug 30 03:42 facter.rb`
`-rw-r--r--. 1 root root  26 Oct 20 10:36 Gemfile.local.rb`
`-rw-r--r--. 1 root root  65 Aug 30 03:42 jsonp.rb`
`-rw-r--r--. 1 root root 129 Aug 30 03:42 postgresql.rb`
`[root@foreman1 bundler.d]# cat Gemfile.local.rb`
`gem 'foreman_fog_proxmox'`
`[root@foreman1 bundler.d]# bundle exec bin/rake plugin:assets:precompile[foreman_fog_proxmox]`
`Could not locate Gemfile or .bundle/ directory`

I've tried as both root and the foreman user with the same error each time. I've tried to run the command in different directories but can't get it to run.

**Comment by tristanrobert** [comment]
Hello, please you need to follow strictly the [installation instructions](https://github.com/tristanrobert/foreman_fog_proxmox#from-gem). They are not specific to this plugin. They are common to all foreman plugins.

**Comment by moofishies** [comment]
I have a new VM up and am trying to follow the sample but I'm a bit confused about the installation instructions. The Debian sample shows running commands as the foreman user before foreman has been installed. But the foreman user is not created until foreman is installed. 

/usr/bin/bundle is also not present until foreman has been installed.

**Comment by moofishies** [comment]
I went ahead and installed foreman and tried to continue with the rest of the steps I run into this:

```
[root@foreman1 bundler.d]# sudo -u foreman /usr/bin/bundle install
Could not locate Gemfile
[root@foreman1 bundler.d]# pwd
/usr/share/foreman/bundler.d
```

**Comment by tristanrobert** [comment]
1 month later I close it. I hope you find the solution.
