### ISSUE TITLE
OVS bridges are not listed when creating a new host in Foreman

### ISSUE THREAD

**Issue by rogerfachini** [tristanrobert/foreman_fog_proxmox#43]
**Describe the bug**
When creating a new host, under the Nic section the dropdown menu for selecting a bridge is empty, even though the Proxmox node has an OpenVirtualSwitch (OVS) bridge in its network config. 

**To Reproduce**
1. Go through the process of creating a new host within Foreman, up until the `interfaces` tab is reached.
2. Click on the `Edit` button for the first interface
3. Scroll down to the Nic section
4. The bridge section is empty, and does not list the OVS bridges available to the system. 

**Expected behavior**
OVS bridges available to the node should be listed in the dropdown menu. 

**Screenshots**

![nic](https://user-images.githubusercontent.com/7243587/47942944-28ce8180-deb1-11e8-977c-4b6785aef66c.PNG)
The OVS bridge is not listed under Foreman. 

![proxnic](https://user-images.githubusercontent.com/7243587/47942952-2cfa9f00-deb1-11e8-848b-80c7f46d3c06.PNG)
The OVS bridge is listed under Proxmox. 

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.77

**Foreman**
 - OS: Ubuntu 18.04
 - foreman_fog_proxmox version: 0.5.3
 - foreman version: 1.19.0

**Proxmox**
  - Version: 5.2-10

**Additional context**
I read through the plugin's code, and this issue appears to be caused on [line 89](https://github.com/tristanrobert/foreman_fog_proxmox/blob/7c47a4109149b19b86ed4aacd5a4bfe322350e2c/app/models/foreman_fog_proxmox/proxmox.rb#L89)  of app/models/foreman_fog_proxmox/proxmox.rb. In this function, only interfaces of type `bridge` are returned, however OVS bridges have the type `OVSBridge`. According to Proxmox's API documentation there also appears to be a type of `any_bridge`, which I assume would return bridges of both types.

**Comment by rogerfachini** [comment]
I just stumbled through the process of getting a dev environment set up (I've never done ruby development before) and I can confirm that changing the type to `any_bridge` does allow the OVS bridge to be present in the list. I'll do further testing to verify it works with normal bridges as well, and if that is successful I'll submit a pull request with the fix.

**Comment by tristanrobert** [comment]
Hello, you are right and your contribution is welcome!
