### ISSUE TITLE
Autocreate netX identifier entry

### ISSUE THREAD

**Issue by hlawatschek** [tristanrobert/foreman_fog_proxmox#46]
Hi!
I had a rough time to understand that it is necessary to add the "netX" identifier for creating a new network interface ;-). At the end walking through the source code helped. 
It would be great if the identifier would be automatically created.

-Mark

**Comment by tristanrobert** [comment]
Hello, a profile can fill net0.

**Comment by hlawatschek** [comment]
Hi, I may miss something, but imo I the network identifier cannot be set in the compute profile.

**Comment by tristanrobert** [comment]
Sorry you are right. It is the interface tab. It is not a plugin form but a foreman form. You should create an issue in the foreman project.

**Comment by hlawatschek** [comment]
Yes, but it would be great if the proxmox compute resource could handle an empty network identifier by just applying the default value in the beackground.
