### ISSUE TITLE
Error: invalid PVE ticket

### ISSUE THREAD

**Issue by hbokh** [tristanrobert/foreman_fog_proxmox#55]
**Describe the bug**
When not using Foreman for app. 8 hours and browsing "Virtual Machines" under "Infrastructure" / "Compute Resources", I get this error:

`There was an error listing VMs: Expected([200]) <=> Actual(401 Unauthorized) excon.error.response :body => "" :cookies => [ ] :headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Date" => "Mon, 10 Dec 2018 18:24:47 GMT" "Expires" => "Mon, 10 Dec 2018 18:24:47 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } :host => "pve.example.com" :local_address => "192.168.1.4" :local_port => 45590 :path => "/api2/json/cluster/resources" :port => 8006 :reason_phrase => "permission denied - invalid PVE ticket" :remote_ip => "192.168.1.200" :status => 401 :status_line => "HTTP/1.1 401 permission denied - invalid PVE ticket\r\n" `

**To Reproduce**
1. Login in the webUI and go to 'Infrastructure --> Compute Resources'
2. Click on 'Proxmox VE'
3. Click on 'Virtual Machines'
4. The above error is shown after `Loading virtual machines information ...`

**Expected behavior**
Get a list of virtual machines in the Proxmox VE.

**Screenshots**
Non applicable (the above text will do).

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Version: 63.0.3

Seems to be not browser related though.

**Additional context**

- pveversion: pve-manager/5.3-5/97ae681d (running kernel: 4.15.18-9-pve)
- Foreman 1.20 on Debian 9.6 Stretch (4GB RAM, 2vCPU)
- foreman_fog_proxmox v0.5.5

When the Foreman-host is rebooted, the issue is gone for a while.\
Restarting `apache2` helps as a temporary workaround.

Merci beaucoup!

**Comment by tristanrobert** [comment]
Hello,
as you can see in [wiki Proxmox API](https://pve.proxmox.com/wiki/Proxmox_VE_API):

> NOTE: Tickets have a limited lifetime of 2 hours. But you can simple get a new ticket by passing the old ticket as password to the /access/ticket method.

**Comment by hbokh** [comment]
Merci.
I can see why you won't fix this issue since it's PVE-related, but... I don't know how to pass the old ticket to PVE through the Foreman webUI; where is the old ticket to be found; etc.
Maybe add an option somewhere to resend / refresh the ticket?

**Comment by neomilium** [comment]
Hello.
I'm have same troubles than @hbokh , after few hours of manipulation using Foreman with this plugin, I have some "Invalid ticket errors".
As workaround, restarting foreman instance does work but not satisfying.

@tristanrobert I will be happy to contribute to your work, can I provide more information about issue when it will happends? Is there is any debug trace you want?

**Comment by tristanrobert** [comment]
Hello,

you can get your last ticket looking at http requests in foreman. Then you can copy/paste to compute resource password input field.

**Comment by pdzionek** [comment]
Hi,
I have the same problem. What do you mean by looking at http requests ? is it somewhere in foreman logs ? or you mean to sniff the traffic ? and does it solve this issue permanently ? or just for another 2 hours ? and if it expires why does not retrieve a new ticket via api ?
