### ISSUE TITLE
Foreman can't delete host without VM

### ISSUE THREAD

**Issue by SISheogorath** [tristanrobert/foreman_fog_proxmox#56]
**Describe the bug**
Foreman fails to delete a node when the VM is no longer existing

error message:
```
Failed to destroy a compute Dev-vh (Proxmox) instance <host name>: 
Expected([200]) <=> Actual(500 InternalServerError) excon.error.response 
:body => "{\"data\":null}" 
:cookies => [ ] 
:headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Content-Length" => "13" "Content-Type" => "application/json;charset=UTF-8" "Date" => "Wed, 12 Dec 2018 14:40:17 GMT" "Expires" => "Wed, 12 Dec 2018 14:40:17 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } 
:host => "<proxmox address>" 
:local_address => "<foreman address>" 
:local_port => 45622 
:path => "/api2/json/nodes/dev-vh001/qemu/110/status/current" 
:port => 8006 
:reason_phrase => "Configuration file 'nodes/dev-vh001/qemu-server/110.conf' does not exist" 
:remote_ip => "<proxmox ip>" 
:status => 500 
:status_line => "HTTP/1.1 500 Configuration file 'nodes/dev-vh001/qemu-server/110.conf' does not exist\r\n" 
```

**To Reproduce**
1. Create a new host in foreman using the proxmox compute resource provider
2. Delete the VM that was created by this host in proxmox
3. Try to delete the host in foreman

**Expected behavior**
The host in foreman is deleted, maybe with a warning or an "Do you want to override"-question.

**Desktop:**
 - OS: Fedora Workstation 29
 - Browser Firefox
 - Version 63.0.3

**Additional context**
This actually doesn't only apply to deleted hosts, but also to hosts that are moved from one vhost to another within a proxmox datacenter.

**Comment by tristanrobert** [comment]
It is a Foreman feature: you could edit your host and disassociate it before deleting it.

**Comment by oviliz** [comment]
In my case it won't allow to Edit the host...
![image](https://user-images.githubusercontent.com/73616/235866986-12801616-7ff9-4da6-9725-4a901f713f3a.png)
